feat : 회원가입 구현 및 비밀번호 시큐리티 적용
lby9906/alarm-todo-list pull request #2
Opened 2024-12-19 12:47 UTC by lby9906

2024-12-19 13:22 UTC, cousim46 requested changes
안녕하세요 민지님 :)
처음 올린 PR이다보니 적지 않은 양의 리뷰를 진행하였습니다!
리뷰 내용을 보시면서 의문이 드는 부분 또는  이해가 안되는 부분이 있다면 코멘트 달아주세요!

2024-12-19 13:22 UTC, cousim46 commented on src/main/java/com/spring/alarm_todo_list/config/SecurityConfig.java
> +}
해당 이슈는 회원가입에 대한 이슈인데 스프링 시큐리티에 대해서 많은 설정을 하신거 같습니다.
회원가입에서 회원의 비밀번호를 암호화 하는 로직만 작업범위에 포함되는거같고 다른 부분은 작업범위를 크게 벗어나신거 같습니다!
작업범위에 맞게 작업해주시면 리뷰어에게 큰 도움이 될거 같습니다!

2024-12-19 13:22 UTC, cousim46 commented on src/main/java/com/spring/alarm_todo_list/application/account/service/AccountWriteService.java
> +@AllArgsConstructor
RequiredArgsConstructor로 사용해서 final로 선언된 값들만 생성자의 매개변수로 만드는게 어떨가요?

2024-12-19 13:22 UTC, cousim46 commented on src/main/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequest.java
> +}
제가 생각했을때 이메일, 닉네임, 핸드폰번호, 비밀번호 모두 값이 있어야하는 요소들로 보입니다.
그런데 이와 같이할 경우 클라이언트에서 값을 보내지 않을 경우 null로 값이 들어오고 데이터베이스에 값이 null로 저장될거 같습니다!
해당 부분을 validation 처리하여 필수값과 선택값을 구분짓는게 어떨까요!

as-is
```java
@Getter
public class AccountRequest {
    private String email;
    private String nickName;
  // 생략
}
```

to-be
```java
@Getter
public class AccountRequest {
   @NotBlank(message="이메일은 필수값입니다.")
    private String email;
    @NotNull(message="닉네임은 필수값입니다.")
    private String nickName;
   //생략
}
```
위와 같이 NotBlank, NotNull로 처리하고 컨트롤러 부분에서는 아래와 같이 하면 필수값인데 값이 안들어올 경우 예외를 반환할 수 있습니다.

Controller

as-is
```java
@PostMapping
public String join(@RequestBody AccountRequest accountRequest) {
    return accountWriteService.join(accountRequest);
}
```

to-be
```java
@PostMapping
public String join(@Valid @RequestBody AccountRequest accountRequest) {
    return accountWriteService.join(accountRequest);
}
```

아래 블로그 참고하시면 좋을거 같습니다.

https://yulee.tistory.com/115

2024-12-19 13:22 UTC, cousim46 commented on src/main/java/com/spring/alarm_todo_list/domain/account/entity/Account.java
> +    private String password;
지금 현재 Account 엔티티를 인스턴스화를 할때 생성자를 통해서 만들고 계시는거 같습니다!
제 개인적인 생각이지만 정적 팩토리를 만들어서 무엇을 하려고 하는것인지 명확하게 나타내는게 어떨까요!
(정적팩토리 메서드란? -> https://olrlobt.tistory.com/70)
그럼 아래와 같이 사용하실 수 있을거 같습니다!

as-is
```java
//Account.class
@Entity
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Account extends BaseEntity {

    private String email;

    private String nickName;

    private String phoneNumber;

    private String password;
}

//AccountWriteService.class
 public String join(AccountRequest accountRequest){
       //생략 - 회원 중복여부 체크로직 

        Account account = new Account(accountRequest.getEmail(), accountRequest.getNickName(), accountRequest.getPhoneNumber(), passwordEncoder.encode(accountRequest.getPassword()));
        accountRepository.save(account);
        return "회원 가입 성공";
    }

public String join
```

to-be
```java
//Account.class
@Entity
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Account extends BaseEntity {

    private String email;

    private String nickName;

    private String phoneNumber;

    private String password;

    public static Account of(String email, String nickName, String phoneNumber, String password) {
        return new Account(email, nickName, phoneNumber, password);
    }
}

//AccountWriteService.class
 public String join(AccountRequest accountRequest){
       //생략 - 회원 중복여부 체크로직 

        Account account = Account.of(accountRequest.getEmail(), accountRequest.getNickName(), accountRequest.getPhoneNumber(), passwordEncoder.encode(accountRequest.getPassword()));
        accountRepository.save(account);
        return "회원 가입 성공";
    }
```
정적 팩토리 메서드를 활용하면 Account 인스턴스를 생성하더라도 용도를 쉽게파악할 수 있다는 장점이 있습니다!

메서드명 of와 from에 대한 차이점은 아래 블로그를 참고하시면 좋을거 같습니다!

메서드명 of와 from의 차이점 ->  https://sy-develop-note.tistory.com/74

2024-12-19 13:22 UTC, cousim46 commented on src/main/java/com/spring/alarm_todo_list/AlarmTodoListApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
SecurityAutoConfiguration 이 부분은 왜 제외시키는지에 대해서 알 수 있을까요?

2024-12-19 13:30 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/exception/ErrorCode.java
> +}
알겠습니다! 새로운 이슈를 생성해서 해당되는 작업들만 모아두도록 하겠습니다.

2024-12-19 13:31 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/exception/AlarmTodoListException.java
> +    private ErrorCode errorCode;
수정하겠습니다.

2024-12-19 13:31 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/domain/account/entity/Account.java
> +    private String password;
좋은것같습니다! 수정하겠습니다.

2024-12-19 13:31 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/config/SecurityConfig.java
> +}
넵 수정하겠습니다.

2024-12-19 13:32 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/application/account/service/AccountWriteService.java
> +@AllArgsConstructor
좋은 방법인 것 같습니다! 수정하겠습니다!

2024-12-19 13:33 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequest.java
> +}
좋은것같습니다! 수정하겠습니다.

2024-12-19 13:33 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/domain/account/entity/Account.java
> +    private String password;
한번 활용해서 구현해보도록 하겠습니다!

2024-12-19 13:37 UTC, lby9906 commented on src/main/java/com/spring/alarm_todo_list/AlarmTodoListApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
Spring Security가 포함되면 자동으로 웹 보안이 적용되어 애플리케이션이 실행될 때 /login 페이지가 제공되거나,
Postman과 같은 툴로 테스트할 때 인증 헤더를 요구하여 요청이 차단될 수 있어 제외시켰습니다.

2024-12-23 11:56 UTC, cousim46 reviewed
여러가지로 시도한 흔적이 보이네요!
아직 테스트 코드 작성에 대해서 습관이 잘 안잡힌 상태이신데 잘 작성하신거 같습니다!
그래도 조금 수정하면 좋을거 같은부분에 대해서 리뷰를 작성하였습니다!
이해 안되는 부분 또는 의문이 드는 부분에 대해서는 편하게 코멘트 달아주세요
고생하셨습니다 :)

2024-12-23 11:56 UTC, cousim46 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
h2는 테스트 환경을 위해서 의존성을 추가해주신거 같은데 testRuntimeOnly로 설정하셔도 될거같습니다!

2024-12-23 11:56 UTC, cousim46 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +class AccountRequestTest {
테스트코드는 정말 잘작성해주셨는데 @DisplayName과 메서드명이 의미가 일치하지 않은거 같습니다!
@DisplayName과 메서드명 의미가 유사하게 변경하시면 좋을거 같습니다!
as-is
```java
 @Test
    @DisplayName("이메일을 작성하지 않는 경우 예외가 발생한다.")
    public void emailValidTest() {}
```

to-be
```java
 @Test
    @DisplayName("이메일을 작성하지 않는 경우 예외가 발생한다.")
    public void occurEmailBlankException() {
```

2024-12-23 11:56 UTC, cousim46 commented on src/test/java/com/spring/alarm_todo_list/domain/account/entity/AccountTest.java
> +        assertThat(createAccount.getPhoneNumber()).isEqualTo(phoneNumber);
email, nickname, phoneNumber, password중에서 phoneNumber에 대해서만 검증하고 게신거 같습니다!
추가적인 다른 데이터들도 검증하시는게 좋을거 같습니다!

2024-12-23 11:56 UTC, cousim46 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +class AccountRequestTest {
추가적으로 AccountRequest에서 모든 변수들에 @NotBlank가 붙어있습니다!
NotBlank 같은 경우에는 ""과 null 일 수 없다라는것을 의미합니다!
그런데 테스트 코드에서는 null인 경우에만 예외가 발생하는 코드를 작성하신거 같습니다!
""에 대한 테스트 코드도 추가하면 좋을거 같습니다!

2024-12-23 13:23 UTC, lby9906 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
넵 알겠습니다.

2024-12-23 13:24 UTC, lby9906 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +class AccountRequestTest {
그렇네요 수정하겠습니다.

2024-12-24 04:43 UTC, lby9906 commented on src/test/java/com/spring/alarm_todo_list/domain/account/entity/AccountTest.java
> +        assertThat(createAccount.getPhoneNumber()).isEqualTo(phoneNumber);
아 빼먹은것같네요! 추가하겠습니다.

2024-12-24 04:50 UTC, lby9906 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +class AccountRequestTest {
넵 알겠습니다!

2024-12-24 13:17 UTC, cousim46 reviewed
리뷰에 대해서 잘 반영해주시고 계신거 같습니다!
이번 리뷰가 마지막 리뷰가 될거 같습니다! 수정 후 말씀해주시면 approve하겠습니다!

2024-12-24 13:17 UTC, cousim46 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +    }
DisplayName은 "핸드폰 번호를 입력할 경우 예외가 발생하지 않는다."라고 작성해주셨는데 메서드명은 "Blank일때 예외가 발생하지 않는다"로 해석이 되는거 같습니다!

2024-12-24 13:17 UTC, cousim46 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +    }
다른 부분도 동일한거 같습니다

2024-12-26 04:14 UTC, lby9906 commented on src/test/java/com/spring/alarm_todo_list/application/account/dto/request/AccountRequestTest.java
> +    }
넵 반영하겠습니다!

2024-12-26 11:33 UTC, cousim46 approved these changes
고생하셨습니다!
프로젝트 초반이라 적지 않은 양의 리뷰를 작성했는데 잘 반영해주셔서 감사합니다!
앞으로 질문 또는 이해 안되는 부분이 있다면 편하게 말씀해주세요!

2024-12-26 11:33 UTC, merged